environment:
  matrix:
    # node.js
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"

install:
  - npm install

test_script:
  - npm test

image:
  - Visual Studio 2017
  - Visual Studio 2015
